-- C and B Potted Plants: schema, access rules and storage.
-- Run once in Supabase → SQL Editor, then run 0002_seed.sql.

-- ---------------------------------------------------------------------------
-- Staff: who may manage products. Roles are granted by email, so an invite
-- works whether the person has signed in before or not.
-- ---------------------------------------------------------------------------
create table public.staff_invites (
  email text primary key check (email = lower(email)),
  role text not null check (role in ('seller', 'admin')),
  created_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users on delete cascade,
  email text not null,
  full_name text,
  avatar_url text,
  role text not null default 'customer' check (role in ('customer', 'seller', 'admin')),
  created_at timestamptz not null default now()
);

-- Create a profile for every new sign-in, picking up any pending staff invite.
create function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url, role)
  values (
    new.id,
    lower(new.email),
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.raw_user_meta_data ->> 'avatar_url',
    coalesce((select i.role from public.staff_invites i where i.email = lower(new.email)), 'customer')
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Role checks used by the policies below. SECURITY DEFINER avoids recursive RLS on profiles.
create function public.app_role() returns text
language sql stable security definer set search_path = '' as $$
  select role from public.profiles where id = auth.uid()
$$;

create function public.is_staff() returns boolean
language sql stable as $$ select coalesce(public.app_role() in ('seller', 'admin'), false) $$;

create function public.is_admin() returns boolean
language sql stable as $$ select coalesce(public.app_role() = 'admin', false) $$;

-- ---------------------------------------------------------------------------
-- Catalogue
-- ---------------------------------------------------------------------------
create table public.products (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  name text not null check (char_length(name) between 1 and 120),
  scientific_name text,
  category text not null check (category in ('Plants', 'Pots', 'Fertilizers', 'Seeds', 'Accessories')),
  description text not null check (char_length(description) between 1 and 2000),
  current_price numeric(10, 2) not null check (current_price >= 0),
  original_price numeric(10, 2) check (original_price >= 0),
  best_seller boolean not null default false,
  stock integer not null default 0 check (stock >= 0),
  family text,
  size text,
  difficulty text,
  light text,
  tags text[] not null default '{}',
  images text[] not null default '{}',
  status text not null default 'live' check (status in ('live', 'draft')),
  seller_id uuid references public.profiles on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index products_category_idx on public.products (category) where status = 'live';

create function public.touch_updated_at() returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger products_touch before update on public.products
  for each row execute function public.touch_updated_at();

create table public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products on delete cascade,
  -- Null for reviews imported from the old site.
  user_id uuid references public.profiles on delete cascade,
  author_name text not null check (char_length(author_name) between 1 and 80),
  rating smallint not null check (rating between 1 and 5),
  comment text not null check (char_length(comment) between 1 and 1000),
  created_at timestamptz not null default now(),
  unique (product_id, user_id)
);

create index reviews_product_idx on public.reviews (product_id);

-- Reviewers can't choose the displayed name: it always comes from their Google profile.
create function public.set_review_author() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if new.user_id is not null then
    select coalesce(nullif(p.full_name, ''), split_part(p.email, '@', 1)) into new.author_name
    from public.profiles p where p.id = new.user_id;
  end if;
  return new;
end;
$$;

create trigger reviews_set_author before insert on public.reviews
  for each row execute function public.set_review_author();

-- ---------------------------------------------------------------------------
-- Row Level Security: the database itself enforces who can do what.
-- ---------------------------------------------------------------------------
alter table public.staff_invites enable row level security;
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.reviews enable row level security;

create policy "admins manage invites" on public.staff_invites
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "read own profile" on public.profiles
  for select to authenticated using (id = auth.uid() or public.is_admin());
create policy "admins change roles" on public.profiles
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "anyone reads live products" on public.products
  for select using (status = 'live' or public.is_staff());
create policy "staff add products" on public.products
  for insert to authenticated with check (public.is_staff() and seller_id = auth.uid());
create policy "owners and admins edit products" on public.products
  for update to authenticated
  using (public.is_admin() or (public.is_staff() and seller_id = auth.uid()))
  with check (public.is_admin() or (public.is_staff() and seller_id = auth.uid()));
create policy "owners and admins delete products" on public.products
  for delete to authenticated using (public.is_admin() or (public.is_staff() and seller_id = auth.uid()));

create policy "anyone reads reviews" on public.reviews for select using (true);
create policy "signed-in users review" on public.reviews
  for insert to authenticated with check (user_id = auth.uid());
create policy "authors and admins delete reviews" on public.reviews
  for delete to authenticated using (user_id = auth.uid() or public.is_admin());

-- ---------------------------------------------------------------------------
-- Product photo storage: public to read, staff-only to write.
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 5242880, array['image/jpeg', 'image/png', 'image/webp']);

create policy "staff upload product images" on storage.objects
  for insert to authenticated with check (bucket_id = 'product-images' and public.is_staff());
create policy "staff delete product images" on storage.objects
  for delete to authenticated using (bucket_id = 'product-images' and public.is_staff());

-- ---------------------------------------------------------------------------
-- Table access for the website. RLS policies above still decide which rows.
-- ---------------------------------------------------------------------------
grant select on public.products, public.reviews to anon, authenticated;
grant insert, update, delete on public.products to authenticated;
grant insert, delete on public.reviews to authenticated;
grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.staff_invites to authenticated;
