-- Initial data: the 17 products and 3 reviews from the old site, plus the first admin.
-- Run once in Supabase → SQL Editor, after 0001_init.sql.

insert into public.staff_invites (email, role) values ('madhubalanpalanivel737@gmail.com', 'admin');

insert into public.products
  (id, slug, name, scientific_name, category, description, current_price, original_price, best_seller, stock,
   family, size, difficulty, light, tags, images, created_at)
overriding system value values
  (1, 'ginseng-ficus-bonsai', 'Ginseng Ficus Bonsai', 'Ficus microcarpa', 'Plants', 'A beautiful bonsai-style plant with glossy green leaves and a distinctive thick, exposed root system.', 999, 1599, true, 15, 'Ficus', 'Up to 50 cm', 'Easy', 'Plenty of light to half shade', array['Bonsai', 'Indoor', 'Tabletop']::text[], array['/images/products/ginseng-ficus-1.jpg', '/images/products/ginseng-ficus-2.jpg', '/images/products/ginseng-ficus-3.jpg', '/images/products/ginseng-ficus-4.jpg']::text[], '2026-08-01'),
  (2, 'echeveria-succulent', 'Echeveria Succulent Plant', 'Echeveria', 'Plants', 'A beautiful rosette-forming succulent with fleshy, pastel blue-green leaves arranged in a compact spiral.', 349, 399, true, 0, 'Other', 'Cutting', 'Intermediate', 'Plenty of light to shade', array['Succulent', 'Low-Maintenance', 'Tabletop']::text[], array['/images/products/echeveria-1.jpg', '/images/products/echeveria-2.jpg']::text[], '2026-08-10'),
  (3, 'serissa-tree-of-a-thousand-stars', 'Tree of a Thousand Stars', 'Serissa japonica', 'Plants', 'A compact bonsai-style ornamental plant with tiny, dense green leaves and fine branching.', 349, 399, false, 25, 'Other', 'Up to 50 cm', 'Intermediate', 'Plenty of light but no direct sunlight', array['Bonsai', 'Tabletop', 'Ornamental']::text[], array['/images/products/serissa-1.jpg', '/images/products/serissa-2.jpg']::text[], '2026-08-12'),
  (4, 'golden-syngonium', 'Golden Syngonium Plant', 'Syngonium podophyllum', 'Plants', 'A tropical indoor plant with attractive arrow-shaped leaves in bright golden-green shades.', 349, 399, true, 41, 'Syngonium', 'Up to 50 cm', 'Easy', 'Plenty of light but no direct sunlight', array['Tropical', 'Indoor', 'Air-Purifying']::text[], array['/images/products/golden-syngonium-1.jpg', '/images/products/golden-syngonium-2.jpg']::text[], '2026-07-20'),
  (5, 'variegated-ming-aralia', 'Variegated Ming Aralia', 'Polyscias fruticosa', 'Plants', 'A compact ornamental plant with finely textured, variegated green-and-cream foliage.', 349, 399, false, 18, 'Other', 'Up to 50 cm', 'Intermediate', 'Plenty of light to shade', array['Ornamental', 'Tabletop', 'Indoor']::text[], array['/images/products/variegated-ming-aralia-1.jpg', '/images/products/variegated-ming-aralia-2.jpg']::text[], '2026-08-15'),
  (6, 'ming-aralia', 'Aralia (Ming Aralia)', 'Polyscias fruticosa', 'Plants', 'A bushy ornamental plant with finely divided, attractive green foliage.', 349, 399, false, 20, 'Other', 'Up to 50 cm', 'Intermediate', 'Plenty of light to shade', array['Ornamental', 'Indoor']::text[], array['/images/products/ming-aralia-1.jpg']::text[], '2026-08-16'),
  (7, 'syngonium', 'Syngonium', 'Syngonium podophyllum', 'Plants', 'Syngonium is a popular tropical indoor plant known for its attractive arrow-shaped leaves.', 349, 399, false, 30, 'Syngonium', 'Up to 50 cm', 'Easy', 'Plenty of light to half shade', array['Tropical', 'Indoor', 'Air-Purifying']::text[], array['/images/products/syngonium-1.jpg', '/images/products/syngonium-2.jpg']::text[], '2026-08-17'),
  (8, 'jade-bonsai', 'Jade Bonsai', 'Crassula ovata', 'Plants', 'A popular succulent with thick, fleshy, oval-shaped glossy green leaves and sturdy woody stems.', 349, 399, true, 40, 'Other', 'Up to 50 cm', 'Easy', 'Plenty of light to half shade', array['Succulent', 'Bonsai', 'Low-Maintenance']::text[], array['/images/products/jade-bonsai-1.jpg', '/images/products/jade-bonsai-2.jpg']::text[], '2026-08-05'),
  (9, 'dwarf-jade', 'Dwarf Jade Plant', 'Portulacaria afra', 'Plants', 'A compact succulent with small, round, glossy green leaves and reddish-brown stems.', 349, 399, false, 35, 'Other', 'Up to 50 cm', 'Easy', 'Plenty of light to half shade', array['Succulent', 'Bonsai', 'Tabletop']::text[], array['/images/products/dwarf-jade-1.jpg']::text[], '2026-08-06'),
  (10, 'polka-dot-plant', 'Polka Dot Plant', 'Hypoestes phyllostachya', 'Plants', 'A colorful ornamental foliage plant with green leaves covered in contrasting spots and splashes.', 349, 399, false, 22, 'Other', 'Up to 50 cm', 'Easy', 'Plenty of light but no direct sunlight', array['Ornamental', 'Indoor', 'Tropical']::text[], array[]::text[], '2026-08-07'),
  (11, 'peperomia-baby-rubber-plant', 'Peperomia', 'Peperomia obtusifolia', 'Plants', 'Baby Rubber Plant (Peperomia obtusifolia) is a compact indoor plant with thick, glossy green leaves.', 349, 399, false, 28, 'Other', 'Up to 50 cm', 'Easy', 'Plenty of light to shade', array['Tropical', 'Indoor', 'Low-Maintenance']::text[], array[]::text[], '2026-08-08'),
  (12, 'monstera-deliciosa', 'Monstera Deliciosa', 'Monstera deliciosa', 'Plants', 'Famous for its natural leaf holes, this tropical plant adds a bold jungle vibe to any room.', 1299, 1499, false, 12, 'Monstera', '50 cm to 100 cm', 'Easy', 'Plenty of light but no direct sunlight', array['Tropical', 'Indoor', 'Air-Purifying']::text[], array['https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=1200&q=80']::text[], '2026-09-01'),
  (13, 'philodendron-birkin', 'Philodendron Birkin', 'Philodendron ''Birkin''', 'Plants', 'A stunning compact plant with dark green leaves featuring striking white pinstripes.', 599, 799, false, 8, 'Philodendron', 'Up to 50 cm', 'Intermediate', 'Plenty of light to half shade', array['Tropical', 'Indoor']::text[], array['https://images.unsplash.com/photo-1599598425947-33002629ddbc?auto=format&fit=crop&w=1200&q=80']::text[], '2026-09-10'),
  (14, 'ceramic-minimalist-pot', 'Ceramic Minimalist Pot', null, 'Pots', 'A beautiful matte ceramic pot with drainage hole and matching saucer. Perfect for modern interiors.', 450, 550, true, 106, null, 'Up to 50 cm', null, null, array['Pots']::text[], array['https://images.unsplash.com/photo-1485955900006-10f4d324d411?auto=format&fit=crop&w=1200&q=80']::text[], '2026-06-15'),
  (15, 'organic-liquid-fertilizer', 'Organic Liquid Fertilizer', null, 'Fertilizers', 'All-natural seaweed extract fertilizer. Promotes lush foliage and strong root growth for all indoor plants.', 299, 350, false, 50, null, null, null, null, array['Fertilizers']::text[], array['https://images.unsplash.com/photo-1622383563227-04401ab4e5ea?auto=format&fit=crop&w=1200&q=80']::text[], '2026-08-05'),
  (16, 'premium-watering-can', 'Premium Watering Can', null, 'Accessories', 'Stainless steel watering can with a long spout for precise watering without spilling.', 899, 1200, false, 0, null, null, null, null, array['Accessories']::text[], array['https://images.unsplash.com/photo-1416879598553-33bc0fbaaf73?auto=format&fit=crop&w=1200&q=80']::text[], '2026-07-01'),
  (17, 'mixed-herb-seeds-bundle', 'Mixed Herb Seeds Bundle', null, 'Seeds', 'A bundle of Basil, Mint, and Coriander seeds ready to be sown in your kitchen garden.', 199, 250, false, 200, null, null, null, null, array['Seeds']::text[], array['https://images.unsplash.com/photo-1588667527653-cb30b4ec74f4?auto=format&fit=crop&w=1200&q=80']::text[], '2026-09-15');

select setval(pg_get_serial_sequence('public.products', 'id'), (select max(id) from public.products));

insert into public.reviews (product_id, author_name, rating, comment) values
  (4, 'Suresh P.', 5, 'Vibrant yellow-green leaves. Growing so fast!'),
  (8, 'Meera W.', 5, 'Sturdy and beautiful. Highly recommend.'),
  (10, 'Anil B.', 4, 'Love the pink spots!');
